name: Continuous Integration (CI)

on: [push]

jobs:
  build-and-test:
    name: Build, Test, and Quality Gate
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/catthehacker/ubuntu:act-24.04
    env:
      DOCKER_HOST: tcp://localhost:2375

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal

    - name: Publish
      run: dotnet publish --no-build --configuration Release

    - name: Docker Login
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login forgejo.anitazheng.org -u zhengt --password-stdin

    - name: Docker Build and Push
      run: |
        docker build -t forgejo.anitazheng.org/zhengt/dotnet-multimodule-app:${{ github.sha }} .
        docker tag forgejo.anitazheng.org/zhengt/dotnet-multimodule-app:${{ github.sha }} forgejo.anitazheng.org/zhengt/dotnet-multimodule-app:latest
        docker push forgejo.anitazheng.org/zhengt/dotnet-multimodule-app:${{ github.sha }}
        docker push forgejo.anitazheng.org/zhengt/dotnet-multimodule-app:latest

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl set image deployment/web-ui web-ui=forgejo.anitazheng.org/zhengt/dotnet-multimodule-app:${{ github.sha }} -n dotnet-app
